### ISSUE TITLE
Release the test images?

### ISSUE THREAD

**Issue by flowice** [ycjing/Neural-Style-Transfer-Papers#1]
Hi, Yongcheng. 
Thanks for your wonderful work.
Would you like to release all your test images and results as a common dataset?
I think it is important to compare with some common testing examples.
Also, I really like the images in your experiments.

**Comment by ycjing** [comment]
Thanks for your interest. This version of our paper is an initial version and may need some modifications according to other researchers' comments in the future. So I think it is more appropriate to release our pre-trained models as well as test images after the peer-review process. 
Nevertheless, if you need these models and images for research purposes now, feel free to send me an email to ask for them.

**Comment by ycjing** [comment]
@flowice  Hi. For the optimizer question we discussed through email last time, today I came across an implementation that has the option of L-BFGS optimizer. His way of implementing L-BFGS in tensorflow is actually the way I have discussed with you. Please check https://github.com/cysmith/neural-style-tf
