### ISSUE TITLE
Dynamic Instance Normalization for Arbitrary Style Transfer

### ISSUE THREAD

**Issue by GlebSBrykin** [ycjing/Neural-Style-Transfer-Papers#12]
Good afternoon! I would like to ask you to use your algorithm to style the two images presented. I'm very interested in how Your algorithm will convey the Starry Night style.
![Content](https://user-images.githubusercontent.com/36363358/75370209-caaf8400-58d5-11ea-9dd7-2623a921ffc4.jpg)
![vangogh_starry_night](https://user-images.githubusercontent.com/36363358/75370225-d00cce80-58d5-11ea-9dfc-dd626b879312.jpg)

**Comment by ycjing** [comment]
Hi @GlebBrykin 

Thank you for your interest in our paper. I am a little busy this week. I will post the result for you after one or two weeks.

Best,
Yongcheng

**Comment by GlebSBrykin** [comment]
Any progress on this?

**Comment by ycjing** [comment]
Hi @GlebBrykin ,

Really sorry for the late response. I was too busy with a recent paper submission, which was just due the day before yesterday. Here are the results of our proposed DIN:

**(1) Standard DIN with kernel_size=1:** 
![content_stylized_style_ori](https://user-images.githubusercontent.com/15648732/76723352-e8a83000-6781-11ea-9fd6-7f2e19afd78c.jpg)

**(2) Standard DIN with kernel_size=3:** 
![content_stylized_style](https://user-images.githubusercontent.com/15648732/76723369-f8277900-6781-11ea-8021-0829828e3cba.jpg)

Please let me know if there is anything else I could help. Thank you again for your interest in our work. 

Best,
Yongcheng

**Comment by ycjing** [comment]
Hi @GlebBrykin ,

Is there any other problem on this issue?
