### ISSUE TITLE
image analogy review

### ISSUE THREAD

**Issue by Hongiee2** [ycjing/Neural-Style-Transfer-Papers#15]
Hi @ycjing , I got a lot of help from the review paper

I wonder if there are review paper about Image Analogy

**Comment by ycjing** [comment]
Hi @Hongiee2 

Thank you very much for your interest in our work. Unfortunately I am not aware of any survey paper on image analogy. But I would recommend you a good paper on image analogy titled "Visual Attribute Transfer through Deep Image Analogy". Maybe you could refer to the related work on image analogy from this paper.

Best,
Yongcheng
