### ISSUE TITLE
could we apply  Neural-Style-Transfer to image deformation?

### ISSUE THREAD

**Issue by erhuodaosi** [ycjing/Neural-Style-Transfer-Papers#16]
I'm sorry to bother you,but I have a question on could we apply Neural-Style-Transfer to image deformation.

In style-transfer,we usually provide a content image and a style image to generate results.And now,could we give a content picture,and let it transform into a warpping image?If the answer is yes,what is the style image?How could we get the style image?

Here are two pictures:one is the original picture,and the other is the transformed image.
![before](https://user-images.githubusercontent.com/45588148/87241533-bb7d3d00-c456-11ea-9e9f-b7120679497a.png)
![after](https://user-images.githubusercontent.com/45588148/87241534-bd470080-c456-11ea-9278-b78cd854a2f7.png)

I would very appreciate if you could help me,thank you!

**Comment by ycjing** [comment]
Hi @erhuodaosi 

Thank you for your interest in our work! Personally, I think that it is a reasonable idea to apply neural style transfer to image deformations. Actually, in my master's studies, I once worked on a project named _"Virtual Mirror"_ that tried to use the idea of style transfer to produce deformed clothes images. However, directly applying existing style transfer algorithms will produce too many artifacts, no matter what the style image is. So I tried to propose a new style transfer algorithm that was specified to image deformations, but unfortunately failed without any satisfying results before graduation. 

I am pleased to see other researchers who are also considering this problem. Please feel free to contact me if there is anything I could help. Thank you for your interest again.

Best,
Yongcheng

**Comment by erhuodaosi** [comment]
@ycjing 

Hi,

Thank you for your timely reply!Thanks a lot!
I am very confused about how to solve the problem and have tried many ways but in vain.Is there any way to deform clothes images except using affine transformation?

Thank you for your patient again.

Best,
FengLang

**Comment by ycjing** [comment]
Hi @erhuodaosi ,

Thank you for the reply! I think that the problem of image deformations might be better studied in the field of computer graphics. But since computer graphics is not my area, I am not able to discuss more details. Really sorry for that.  

Best,
Yongcheng

**Comment by erhuodaosi** [comment]
@ycjing

Hi,

Thank you for your timely reply!Thanks a lot!

It's a pity that you have no more ideas on how to transform the image.But at the same time, I'm happy about it.At least,I have known that using style transfer is a bad way to solve the problem.And as a result,it helps me save a lot of time.

Thank you for your patient again,really,really...

Best wishes,
FengLang

**Comment by ycjing** [comment]
Hi @erhuodaosi 

It's my pleasure. Thank you for your interests again. Please feel free to contact me if there are further questions. Wish you all the best with your research in image deformation!

Best,
Yongcheng
