### ISSUE TITLE
pystiche: A Framework for Neural Style Transfer

### ISSUE THREAD

**Issue by pmeier** [ycjing/Neural-Style-Transfer-Papers#17]
Hey everyone. I'm building a framework for Neural Style Transfer (NST) called [`pystiche`](https://github.com/pmeier/pystiche). It is build upon and fully compatible with [PyTorch](https://pytorch.org). It provides functionality for the most common NST operators, the efficient encoding of images on multiple layers of a CNN, as well as the periphery around the core parts. It is modular and can be easily extended with new functionality. 

`pystiche` was peer-reviewed by [pyOpenSci](https://github.com/pyOpenSci/software-review/issues/25) and is published in the [Journal of Open Source Software (JOSS)](https://joss.theoj.org/papers/10.21105/joss.02761). I would be happy if it could be added to the list compiled in this repository. 

Let me know if you have questions.

**Comment by ycjing** [comment]
Hi @pmeier 

Thank you for this great work! I have added this nice framework in the repo. Please let me if there is anything else I could help.

Best,
Yongcheng

**Comment by pmeier** [comment]
Thanks for the fast response. I'm in the process of writing a package that comprises reference implementations of NST papers with `pystiche`: it is called [`pystiche_papers`](https://github.com/pmeier/pystiche_papers). It is currently still in a WIP state so I leave it up to you if you want to add it to your list. If you do, please note its current status to avoid confusion.

**Comment by ycjing** [comment]
Hi @pmeier 

Thank you for this nice work! I have noted the current status of pystiche_papers in the repo.

Best,
Yongcheng
