### ISSUE TITLE
NeuralStyler 

### ISSUE THREAD

**Issue by rupeshs** [ycjing/Neural-Style-Transfer-Papers#3]
In the applications section could please add NeuralStyler (windows and linux)
http://neuralstyler.com/

**Comment by ycjing** [comment]
Sure. I will add it in our new version of the paper.

**Comment by ycjing** [comment]
Hi, @rupeshs  I have added your work in our paper. Please check the latest version at: https://arxiv.org/pdf/1705.04058.pdf
Appreciate the feedback!

**Comment by RoyiAvital** [comment]
Could you add [Style Separation and Synthesis via Generative Adversarial Networks](https://arxiv.org/abs/1811.02740)?
