### ISSUE TITLE
about test image

### ISSUE THREAD

**Issue by suke27** [ycjing/Neural-Style-Transfer-Papers#7]
Hi, I found the images you release seems not same with paper, could you share all test images.
another problem is how do you select style image, by genre of art?
Thank you!

**Comment by ycjing** [comment]
Hi, @suke27 . Thanks for your interest. 
1. Currently, our paper is under a major revision. In a newer version of our paper, I have replaced the content images with some higher-quality photos from flickr, which are exactly what I have released. Example comparison results can be found in the supplementary material (http://yongchengjing.com/pdf/review_supp.pdf).
2. Regarding the problem of the style images, I tried to select diverse styles. The following descriptions will be found in a newer version of our paper on arxiv soon:
"_For the style images, we select the artworks of diverse styles, as is shown in Fig. 4. For example, there are impressionism artwork, cubism artwork, abstract artwork, contemporary artwork, futurism artwork, surrealist artwork, and expressionism artwork. Regarding the mediums, some of these artworks are painted on canvas, while others are painted on cardboard or wool, cotton, polyester, etc._"

If there is any question, please let me know. Thanks!
