### ISSUE TITLE
style transfer focus human face 

### ISSUE THREAD

**Issue by lisiping0817** [ycjing/Neural-Style-Transfer-Papers#8]
hi i wonder to know some  paper about the style transfer focus human face .Do  you have some recommend about this field？ thanks

**Comment by suke27** [comment]
is there paper focus on human face?

**Comment by lisiping0817** [comment]
> is there paper focus on human face?

yes  it means style transfer on human face

**Comment by suke27** [comment]
what is special? control transfer area, do you know the paper name

**Comment by lisiping0817** [comment]
> what is special? control transfer area, do you know the paper name

i know a new paper about this field，but no  open source code

**Comment by ycjing** [comment]
Hi, @lisiping0817  Maybe this one:
[Painting Style Transfer for Head Portraits Using Convolutional Neural Networks] [Paper] (SIGGRAPH 2016)

**Comment by lisiping0817** [comment]
> Hi, @lisiping0817 Maybe this one:
> [Painting Style Transfer for Head Portraits Using Convolutional Neural Networks] [Paper] (SIGGRAPH 2016)

thanks

**Comment by lisiping0817** [comment]
> Hi, @lisiping0817 Maybe this one:
> [Painting Style Transfer for Head Portraits Using Convolutional Neural Networks] [Paper] (SIGGRAPH 2016)

could you find this paper open source code?  thank you

**Comment by ycjing** [comment]
@lisiping0817 Unfortunately, I don't find any corresponding code. You may send an email to the author.

**Comment by lisiping0817** [comment]
> @lisiping0817 Unfortunately, I don't find any corresponding code. You may send an email to the author.

ok  thanks a lot
